[package]
name = "ld42"
version = "0.1.0"
authors = ["Ryan Goldstein <ryanisaacg@gmail.com>"]

[dependencies]
nalgebra = "0.15.0"
ncollide2d = "0.16.0"
quicksilver = { git = "https://github.com/ryanisaacg/quicksilver", branch = "ludum-dare"}
